name: Generate Snake Game

on:
  schedule:
    - cron: "0 */6 * * *"  # A cada 6 horas
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jobs to update snake grid
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ysabellyysa  # SEU USERNAME AQUI
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
