name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar pasta dist
        run: mkdir -p dist

      - name: Gerar snake SVG (normal)
        uses: Platane/snk@v3
        with:
          github_user_name: SEU-USUARIO
          output: dist/github-contribution-grid-snake.svg

      - name: Gerar snake SVG (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: SEU-USUARIO
          output: dist/github-contribution-grid-snake-dark.svg
          palette: github-dark

      - name: Publicar no branch "output"
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



